packages:
  - package: calogica/dbt_date
    version: [">=0.7.0", "<0.8.0"]
    # <see https://github.com/calogica/dbt-date/releases/latest> for the latest version tag
  - package: dbt-labs/codegen
    version: 0.9.0