version: 2

models:
  - name: geographical_referential.sql
    description : table of reference for every geographical information of every city in France
    columns:
      - name: municipality_code
        description : code of each municipality/city in France

      - name: city_name
        description : name of city in France

      - name: city_name_normalized
        description : upper name for every city name

      - name: municipality_type
        description : type municipality which is a city and "arrondissement" which is part of a big city

      - name: latitude
        description : latitude coordinate of municipality

      - name: longitude
        description : longitude coordinate of municipality

      - name: department_code
        description : every department code in France

      - name: epci_code
        description : code to gather agglomeration

      - name: country_code
        description : code of department

      - name: department_name
        description : name of the department
        
  - name: profitability_m2.sql
    description : calculation of profitability of each city in term of investment over avg rent per square meter
    columns:
      - name: profitability
        description : safe divide of price per square meter and avg rent per square meter 

      - name: municipality_code
        description : code of each municipality/city in France

      - name: epci_code
        description : code of agglomeration

      - name: department_code
        description : code of department

      - name: municipality_type
        description : type municipality which is a city and "arrondissement" which is part of a big city

      - name: latitude
        description : latitude coordinate of municipality

      - name: longitude
        description : longitude coordinate of municipality