version: 2

models:
  - name: stg_POI_tourist_establishments
    description: Etablissements de vacances (Pierre&Vacances, Club Med…) avec leurs coordonnées géographique et importance
    columns: 
      - name: geographic_id
        description: Primary key
        tests:
          - unique
          - not_null
      - name: poi
        description: Type of establishments
        tests:
          - not_null
      - name: name
        description: Name of the establishments
        tests:
          - not_null
      - name: latitude 
        tests:
          - not_null
      - name: longitude
        tests:
          - not_null
      - name: municipality_code
        tests:
          - not_null
      - name: importance
        description: To define
        tests:
          - not_null
      - name: name_reprocessed
        description: Column name reprocessed with lower and without the poi
        tests:
          - not_null

  - name: stg_average_salary_by_municipality
    columns:
      - name: municipality_year_id
        description: Primary key
        tests:
          - unique
          - not_null
      - name: municipality_code
        tests:
          - not_null
      - name: avg_net_salary
        tests:
          - not_null
      - name: year_year
        tests:
          - not_null
      - name: country_code
        tests:
          - not_null

  - name: stg_housing_stock
    description: Evolution of nb of principal, secondary and vacant houses by municipality and year (over 50 years, every 7-8 years)
    columns:
      - name: municipality_year_id
        description: Primary key
        tests:
          - unique
          - not_null
      - name: municipality_code
        tests:
          - not_null
      - name: year_year
        tests:
          - not_null
      - name: nb_principal_home
        tests:
          - not_null
      - name: nb_second_home
        tests:
          - not_null
      - name: nb_vacants_home
        tests:
          - not_null
      - name: nb_tot_home
        description: addition of principal, second and vacants home
        tests:
          - not_null
      - name: country_code
        tests:
          - not_null        